server:
   port: 80
spring:
  datasource:
    url: jdbc:mysql://116.62.136.149:3306/spring_boot_stu?useSSL=false&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
    username: root
    password: 1qaz@WSX3edc
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
     # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化
    initialSize: 3
    # 最大
    maxActive: 20
    # 最小
    minIdle: 3
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000

    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    #filters: stat, wall, log4j

#配置 Jpa
  jpa:
    mapping-resources:
      - config/db/mysql/db-mysql-sys_user-selection-orm.xml
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
